### ISSUE TITLE
Instructions not clear enough, dick got stuck in toaster.

### ISSUE THREAD

**Issue by Tanmay2k3** [UniverseCodes/nodecp#1]
Instructions not clear enough, dick got stuck in toaster.

**Comment by UniverseCodes** [comment]
lmao tanmay. Did you plug in the toaster? Should've worked.

**Comment by Tanmay2k3** [comment]
Toaster plug got stuck in the wall socket

**Comment by UniverseCodes** [comment]
Weird. It should work. Toaster Version?
